image: registry.gitlab.com/boykioyb/hangkenh:latest

stages:
  - deploy

deploy_dev:
  environment: dev
  stage: deploy
  only:
    - dev
  before_script:
    - 'command -v ssh-agent >/dev/null || ( apk add --update openssh )'
    - eval $(ssh-agent -s)
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - ssh-keyscan -H 1.53.252.75 >> ~/.ssh/known_hosts
    - chmod 644 ~/.ssh/known_hosts
  script:
#    - if [[ -z "${DEPLOY_HOST}" || -z "${PROJECT_LOCATION_DEV}" ]]; then echo "Need to set variables"; exit 1; fi
    - bash ci-cd/runner/runner.deploy.sh "$DEPLOY_HOST" "$PROJECT_LOCATION_DEV"
  when: on_success






#stages:
#  - deploy_dev
#  - migration_dev
#
#deploy_dev:
#  stage: deploy_dev
#  only:
#    - dev
#  before_script:
#    - 'command -v ssh-agent >/dev/null || ( apk add --update openssh )'
#    - eval $(ssh-agent -s)
#    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -
#    - mkdir -p ~/.ssh
#    - chmod 700 ~/.ssh
#  #    - ssh-keyscan $VM_IPADDRESS >> ~/.ssh/known_hosts
#  #    - chmod 644 ~/.ssh/known_hosts
#  script:
#    - ssh $DEPLOY_HOST
#    - 'cd /data/www/hangkenh'
#    - 'git pull origin dev'
#    - 'composer install'
#    - 'npm run build'
#    - 'php artisan cache:clear'
#    - 'php artisan config:clear'
#    - 'php artisan storage:link'
#migration_dev:
#  stage: migration_dev
#  only:
#    - dev
#  script:
#    - 'cd /data/www/hangkenh && php artisan migrate'
